name: Build and Publish Java Library

on:
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_PRIV_KEY }}
          gpg-passphrase: MAVEN_CENTRAL_GPG_PASSPHRASE
      - name: Create Maven security settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings-security.xml <<EOF
          <settingsSecurity>
            <master></master>
          </settingsSecurity>
          EOF
      - name: Set release version
        if: github.event_name == 'release'
        run: |
          TAG="${{ github.event.release.tag_name }}"
          TAG="${TAG#v}"
          mvn -B -f pom.xml versions:set -DnewVersion="$TAG" -DgenerateBackupPoms=false
      - name: Build
        run: mvn -B -f pom.xml verify
      - name: Publish to GitHub Packages
        if: github.event_name == 'release'
        run: mvn -B -f pom.xml deploy -P release
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
